### ISSUE TITLE
Import error when pip installing on repl.it and using BiSC

### ISSUE THREAD

**Issue by ulfarsson** [PermutaTriangle/Permuta#109]
```python
from permuta import *
from permuta.bisc import *
from permuta.bisc.permsets.perm_properties import stack_sortable
```
causes an error.

**Comment by ulfarsson** [comment]
This seems to be fine if one is running inside the Permuta directory. Otherwise not

**Comment by enadeau** [comment]
You're missing and `__init__` file in the permuta/bisc/permsets hence `permuta.bisc.permsets` won't be recognized as a proper python package. This is probably what causes your issue.
