### ISSUE TITLE
Dependency on sympy

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Permuta#119]
The file `permuta/bisc/permsets/perm_properties.py` import some stuff from `sympy` but `sympy` is not listed as a dependency in the `setup.py`. For the next release we need to either add `sympy` as dependency of remove it from `perm_properties.py`.

**Comment by ulfarsson** [comment]
Add it as a dependency is probably easiest. We require it for Tilings anyway.

**Comment by JonSteinn** [comment]
This issue has been solved (#122), issue can be closed.
