### ISSUE TITLE
Implement "All nearest smaller values"

### ISSUE THREAD

**Issue by SuprDewd** [PermutaTriangle/Permuta#16]
Not too important, but it would be cool to implement the O(n) version for Permutation._left_to_right_details

**Comment by RagnarArdal** [comment]
I've just remembered why we didn't do the O(n) all nearest smaller/bigger values. It's because we aren't looking for the _nearest_ smaller/bigger values, but _the_ smaller/values. Do you reckon that's possible in linear time?

**Comment by RagnarArdal** [comment]
I did a thing in permuta/misc called left_floor_and_ceiling. It can probably be done better.
