### ISSUE TITLE
__debug__ for performance

### ISSUE THREAD

**Issue by RagnarArdal** [PermutaTriangle/Permuta#39]
I just found out about the [__debug__ constant in python](https://docs.python.org/3/library/constants.html) which is apparently used to optimize away things away. So for example, the loop in
```python
for n in range(10000):
    if __debug__:
        print(n)
```
will be completely removed from the code if compiled with the optimize flag.
We could use this for our Perm constructor and whatnot. That is, only do the expensive sanity checks on the input to the constructor if __debug__ is True.

Sources:
[A StackOverflow question](https://stackoverflow.com/questions/2830358/what-are-the-implications-of-running-python-with-the-optimize-flag)
[Another one](https://stackoverflow.com/questions/2830358/what-are-the-implications-of-running-python-with-the-optimize-flag)
I haven't gone throught the docs properly yet, but word on the SO-street is that it is da bomb

**Comment by christianbean** [comment]
We have decided to not do this.
