### ISSUE TITLE
Implement insertion index and Kuszmaul methods

### ISSUE THREAD

**Issue by RagnarArdal** [PermutaTriangle/Permuta#40]
I just realized that our generic Avoidance Class is very basic at the moment; just inserting a new maximum in every possible place and checking for avoidance. We should be remembering viable insertion indices. And maybe we could use Kuszmaul's methods to speed us up some. Implementing these should be very simple, and shouldn't take but a day, with some performance considerations.

**Comment by christianbean** [comment]
I feel like this is handled by PR #93. This was not Kuszmaul's algorithm, but does use the insertion indices idea, so closing the issue.
