### ISSUE TITLE
Cache getting to big

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Permuta#78]
If you want to compute the permutation in a lot of classes. The cache get too big and fill the memory. A workaround is to use the above code snippet to clear the cache.

```python
from permuta._perm_set.unbounded.described.avoiding.avoiding import AvoidingGeneric
AvoidingGeneric._AvoidingGeneric__CLASS_CACHE = {}
```

Of course something better should be implemented.

**Comment by JonSteinn** [comment]
#130 offers a more straightforward way of doing this
`Av.clear_cache()`

**Comment by JonSteinn** [comment]
#130 
I also added an auto-cleaning mechanism for cached level lists that are unused for further expansions.
```py
def _ensure_level(self, level_number: int) -> None:
    start = max(0, len(self.cache) - 2)
    # <level expansions happens here>
    for i in range(start, level_number - 1):
        self.cache[i] = {perm: None for perm in self.cache[i]}
```

**Comment by enadeau** [comment]
#130 closed this issue
